### ISSUE TITLE
Not able to see OTel traces across beaconEndpoint

### ISSUE THREAD

**Issue by vikashpisces** [signalfx/splunk-otel-react-native#18]
Hi Team,

 I was trying to integrate splunk-otel-react-native with one of my react-native android app by following the readme guide. Below is my configuration and initialization done in index.ts of RN:
 
 ```javascript
import { SplunkRum } from '@splunk/otel-react-native';

const Rum = SplunkRum.init({
  beaconEndpoint: 'http://localhost:3002/api/v1/traces/ingest', // trying to send traces to an external endpoint, currently running it locally
  applicationName: appName, // reading from app.json
  debug: true,
  rumAccessToken: 'test'
});
```

I can see logs are getting generated in Metro server console saying:

` DEBUG  Exporting:toNativeSpan:  AppStart [1, 96000000]
 DEBUG  AppStart: timeout end 2023-01-25T10:57:57.955Z
 DEBUG  Session:hasExpired 5712327 8687673
 DEBUG  Session:hasTimedOut: State.FOREGROUND
 DEBUG  Session:bump: 2023-01-25T12:33:09.825Z
 DEBUG  Session:hasExpired 5712339 8687661
 DEBUG  Session:hasTimedOut: State.FOREGROUND
 DEBUG  Session:bump: 2023-01-25T12:33:09.836Z
 DEBUG  Exporting:toNativeSpan:  Created [0, 1250795]
 DEBUG  Exporting:toNativeSpan:  HTTP GET [1, 14731168]`

Howev, I could not see any trace data getting posted to the endpoint configured. I tried passing zipkin exporter URL too but could not see any trace coming in my locally running zipkin.

Kindly help.

**Comment by mhennoch** [comment]
Is your android app configured to work with http(eg. setting `android:usesCleartextTraffic="true"`)? And what is your react native version?
